### ISSUE TITLE
Changes made to a file doesn't save when clicking to a different file and then clicking back to the original file

### ISSUE THREAD

**Issue by evaxliu** [sys-bio/AntimonyEditor#27]
Changes only seem to save when the page is refreshed with the current view being that file after changes is made to that file. If I make changes to 1.ant and then click on 2.ant, when I click back to 1.ant the changes disappear.

**Comment by Edih112** [comment]
Commenting out the db update in `handleFileClick` in `App.tsx` appears to fix this issue. Still need to check if this breaks anything else though.
![image](https://github.com/sys-bio/AntimonyEditor/assets/82477579/139f6702-72c1-4712-8d4f-ef5a0e747f59)

**Comment by evaxliu** [comment]
Sounds good thanks.
