### ISSUE TITLE
Don't complain about built-in constants

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/AntimonyEditor#39]
Some variables are pre-defined in Antimony, and don't need to have a red squiggle, since it's defined elsewhere, i.e.

S1->S2; time*S1

'time' is predefined, and shouldn't get a red squiggle.  The full list of predefined constants in Antimony is:

  , "true"
  , "false"
  , "True"
  , "False"
  , "TRUE"
  , "FALSE"
  , "pi"
  , "exponentiale" 
  , "avogadro"  
  , "time"
  , "inf"  
  , "INF"
  , "infinity"
  , "NaN"
  , "NAN"
  , "nan"
  , "notanumber"

**Comment by Edih112** [comment]
Would these built in constants have different hover information from non built-in values?

**Comment by Edih112** [comment]
For example right now with fixed squiggles the hover would just treat it as a normal initialized variable.
![image](https://github.com/user-attachments/assets/595944cd-7446-4c92-a80c-732a4dc44cb5)

**Comment by luciansmith** [comment]
It's not a parameter, and if the user looks for one, they won't find it.  So I think I'd either give it no hover at all, or a new 'predefined constant/variable' hover.  ('time' is a predefined variable; everything else is a predefined constant.)
